[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd src && npm ci --legacy-peer-deps"]

[phases.build]
cmds = ["cd src && npx prisma generate && npm run build"]

[start]
cmd = "cd src && npm start"
